In [11]:
import pandas as pd

The CSV with out sales data is imported from Kaggle. Below I'll import it, get a slice, then output the basic metrics.

In [12]:
df = pd.read_csv(r"../Data/data_raw.csv", encoding="latin1")
df.head();
df.info();
df.describe();

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [13]:
print(df.isnull().sum());
print(df.duplicated().sum());

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64
0

First conlusions: 21 columns, 10k rows. No empty rows or duplicates. I'll group some columns to get early insights into Sales & profit per location and product category.

In [14]:
df_location = df.groupby('State')[['Sales','Profit']].sum().sort_values(by='Sales', ascending=False).copy()
df_location['% profit'] = (df_location['Profit'] / df_location['Sales']) * 100
df_location.head(10)

                    Sales      Profit   % profit
State
California    457687.6315  76381.3871  16.688541
New York      310876.2710  74038.5486  23.816082
Texas         170188.0458 -25729.3563 -15.118192
Washington    138641.2700  33402.6517  24.092863
Pennsylvania  116511.9140 -15559.9603 -13.354823
Florida        89473.7080  -3399.3017  -3.799219
Illinois       80166.1010 -12607.8870 -15.727205
Ohio           78258.1360 -16971.3766 -21.686405
Michigan       76269.6140  24463.1876  32.074618
Virginia       70636.7200  18597.9504  26.329012

Where outliers are interesting to explore:

In [15]:
top_sales = df_location.nlargest(5, 'Sales')
top_profit = df_location.nlargest(5, 'Profit')
bottom_profit = df_location.nsmallest(5, 'Profit')
biggest_performer = df_location.nlargest(5, '% profit')
biggest_underperformer = df_location.nsmallest(5, '% profit')

print(top_sales)
print(top_profit)
print(bottom_profit)
print(biggest_performer)
print(biggest_underperformer)

                    Sales      Profit   % profit
State
California    457687.6315  76381.3871  16.688541
New York      310876.2710  74038.5486  23.816082
Texas         170188.0458 -25729.3563 -15.118192
Washington    138641.2700  33402.6517  24.092863
Pennsylvania  116511.9140 -15559.9603 -13.354823
                  Sales      Profit   % profit
State
California  457687.6315  76381.3871  16.688541
New York    310876.2710  74038.5486  23.816082
Washington  138641.2700  33402.6517  24.092863
Michigan     76269.6140  24463.1876  32.074618
Virginia     70636.7200  18597.9504  26.329012
                      Sales      Profit   % profit
State
Texas           170188.0458 -25729.3563 -15.118192
Ohio             78258.1360 -16971.3766 -21.686405
Pennsylvania    116511.9140 -15559.9603 -13.354823
Illinois         80166.1010 -12607.8870 -15.727205
North Carolina   55603.1640  -7490.9122 -13.472097
                          Sales      Profit   % profit
State
District of Columbia   2865.020   1059.5893  36.983662
Delaware              27451.069   9977.3748  36.346034
Minnesota             29863.150  10823.1874  36.242618
Maine                  1270.530    454.4862  35.771387
Arkansas              11678.130   4008.6871  34.326447
                 Sales      Profit   % profit
State
Ohio        78258.1360 -16971.3766 -21.686405
Colorado    32108.1180  -6527.8579 -20.330864
Tennessee   30661.8730  -5341.6936 -17.421289
Illinois    80166.1010 -12607.8870 -15.727205
Texas      170188.0458 -25729.3563 -15.118192

In [16]:
df_category = df.groupby('Sub-Category')[['Sales', 'Profit']].sum().sort_values(by='Sales', ascending=False).copy()
df_category['% profit'] = (df_category['Profit'] / df_category['Sales']) * 100
df_category.head(10)

                    Sales      Profit   % profit
Sub-Category
Phones        330007.0540  44515.7306  13.489327
Chairs        328449.1030  26590.1663   8.095673
Storage       223843.6080  21278.8264   9.506113
Tables        206965.5320 -17725.4811  -8.564460
Binders       203412.7330  30221.7633  14.857361
Machines      189238.6310   3384.7569   1.788618
Accessories   167380.3180  41936.6357  25.054700
Copiers       149528.0300  55617.8249  37.195585
Bookcases     114879.9963  -3472.5560  -3.022768
Appliances    107532.1610  18138.0054  16.867517

Again looking for outliers:

In [17]:
top_sales = df_category.nlargest(5, 'Sales')
top_profit = df_category.nlargest(5, 'Profit')
bottom_profit = df_category.nsmallest(5, 'Profit')
biggest_performer = df_category.nlargest(5, '% profit')
biggest_underperformer = df_category.nsmallest(5, '% profit')

print(top_sales)
print(top_profit)
print(bottom_profit)
print(biggest_performer)
print(biggest_underperformer)

                   Sales      Profit   % profit
Sub-Category
Phones        330007.054  44515.7306  13.489327
Chairs        328449.103  26590.1663   8.095673
Storage       223843.608  21278.8264   9.506113
Tables        206965.532 -17725.4811  -8.564460
Binders       203412.733  30221.7633  14.857361
                   Sales      Profit   % profit
Sub-Category
Copiers       149528.030  55617.8249  37.195585
Phones        330007.054  44515.7306  13.489327
Accessories   167380.318  41936.6357  25.054700
Paper          78479.206  34053.5693  43.391837
Binders       203412.733  30221.7633  14.857361
                    Sales      Profit   % profit
Sub-Category
Tables        206965.5320 -17725.4811  -8.564460
Bookcases     114879.9963  -3472.5560  -3.022768
Supplies       46673.5380  -1189.0995  -2.547695
Fasteners       3024.2800    949.5182  31.396504
Machines      189238.6310   3384.7569   1.788618
                   Sales      Profit   % profit
Sub-Category
Labels         12486.312   5546.2540  44.418672
Paper          78479.206  34053.5693  43.391837
Envelopes      16476.402   6964.1767  42.267582
Copiers       149528.030  55617.8249  37.195585
Fasteners       3024.280    949.5182  31.396504
                    Sales      Profit  % profit
Sub-Category
Tables        206965.5320 -17725.4811 -8.564460
Bookcases     114879.9963  -3472.5560 -3.022768
Supplies       46673.5380  -1189.0995 -2.547695
Machines      189238.6310   3384.7569  1.788618
Chairs        328449.1030  26590.1663  8.095673

Now we got some basic info on sales per location and category. I now want to analyse the sales and profit over time. Im interested in the data per quarter per year.

In [18]:
df_extended = df.copy()
df_extended['Year'] = pd.to_datetime(df_extended['Order Date']).dt.year
df_extended['Quarter'] = pd.to_datetime(df_extended['Order Date']).dt.quarter
df_extended.groupby(['Year', 'Quarter'])[['Sales', 'Profit']].sum().sort_values(by='Year', ascending=True).head(10)

                    Sales      Profit
Year Quarter
2014 1         74447.7960   3811.2290
     2         86538.7596  11204.0692
     3        143633.2123  12804.7218
     4        179627.7302  21723.9541
2015 1         68851.7386   9264.9416
     2         89124.1870  12190.9224
     3        130259.5752  16853.6194
     4        182297.0082  23309.1203
2016 1         93237.1810  11441.3708
     2        136082.3010  16390.3394

And then finally also a percentage growth added as a column. To visualise it later we will make a new dataframe out of this.

In [19]:
df_trend = df_extended.groupby(['Year', 'Quarter'])[['Sales', 'Profit']].sum().sort_values(by='Year', ascending=True).copy()
df_trend['Sales Growth'] = df_trend['Sales'].pct_change() * 100
df_trend['Profit Growth'] = df_trend['Profit'].pct_change() * 100
df_trend

                    Sales      Profit  Sales Growth  Profit Growth
Year Quarter
2014 1         74447.7960   3811.2290           NaN            NaN
     2         86538.7596  11204.0692     16.240862     193.975230
     3        143633.2123  12804.7218     65.975585      14.286351
     4        179627.7302  21723.9541     25.060024      69.655807
2015 1         68851.7386   9264.9416    -61.669761     -57.351495
     2         89124.1870  12190.9224     29.443626      31.581211
     3        130259.5752  16853.6194     46.155134      38.247286
     4        182297.0082  23309.1203     39.949027      38.303350
2016 1         93237.1810  11441.3708    -48.854245     -50.914618
     2        136082.3010  16390.3394     45.952826      43.255032
     3        143787.3622  15823.6048      5.662060      -3.457736
     4        236098.7538  38139.8593     64.199934     141.031420
2017 1        123144.8602  23506.2026    -47.841800     -38.368408
     2        133764.3720  15499.2085      8.623593     -34.063325
     3        196251.9560  26985.1325     46.714669      74.106520
     4        280054.0670  27448.7260     42.701287       1.717959

Here we see some periodicity to sales YoY. There is a suggested sales drop in Q1 of every year.  YoY analysis, by comparing the quarters, could confirm this.

In [20]:
df_trend['Sales_Growth_YoY'] = df_trend['Sales'].pct_change(periods=4) * 100
df_trend['Profit_Growth_YoY'] = df_trend['Profit'].pct_change(periods=4) * 100
df_trend

                    Sales      Profit  Sales Growth  Profit Growth  \
Year Quarter
2014 1         74447.7960   3811.2290           NaN            NaN
     2         86538.7596  11204.0692     16.240862     193.975230
     3        143633.2123  12804.7218     65.975585      14.286351
     4        179627.7302  21723.9541     25.060024      69.655807
2015 1         68851.7386   9264.9416    -61.669761     -57.351495
     2         89124.1870  12190.9224     29.443626      31.581211
     3        130259.5752  16853.6194     46.155134      38.247286
     4        182297.0082  23309.1203     39.949027      38.303350
2016 1         93237.1810  11441.3708    -48.854245     -50.914618
     2        136082.3010  16390.3394     45.952826      43.255032
     3        143787.3622  15823.6048      5.662060      -3.457736
     4        236098.7538  38139.8593     64.199934     141.031420
2017 1        123144.8602  23506.2026    -47.841800     -38.368408
     2        133764.3720  15499.2085      8.623593     -34.063325
     3        196251.9560  26985.1325     46.714669      74.106520
     4        280054.0670  27448.7260     42.701287       1.717959

              Sales_Growth_YoY  Profit_Growth_YoY
Year Quarter
2014 1                     NaN                NaN
     2                     NaN                NaN
     3                     NaN                NaN
     4                     NaN                NaN
2015 1               -7.516754         143.095904
     2                2.987595           8.807989
     3               -9.310964          31.620348
     4                1.486006           7.296859
2016 1               35.417323          23.491019
     2               52.688407          34.447082
     3               10.385253          -6.111534
     4               29.513236          63.626335
2017 1               32.076988         105.449181
     2               -1.703329          -5.436928
     3               36.487625          70.537200
     4               18.617342         -28.031392

Indeed a recurring seasonal pattern is visible in the data. YoY remains positive for most quarters, indicating that the business does continue to grow despite these drops.

This is it for the EDA (exploratory data analysis) part. Last step is to convert the created dataframes back to CSV

In [21]:
df_location.to_csv("../Data/df_location_summary.csv")
df_category.to_csv("../Data/df_category_summary.csv")
df_trend.to_csv("../Data/df_trend_summary.csv")
df_extended.to_csv("../Data/clean_sales_data.csv", index=False)